In [2]:
## We will work on the Model using different different parameters
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import datasets


In [3]:
datasets.load_breast_cancer()


{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [4]:
X,y=datasets.load_breast_cancer(return_X_y=True)

In [5]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [8]:
y_test

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [9]:
! pip install xgboost

You should consider upgrading via the '/Users/sanju/Documents/DS/MLOps/MLOps_udemy/myenv/bin/python3 -m pip install --upgrade pip' command.


In [10]:
## as our data is ready for the training lets import the models which we gonna use 
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score,accuracy_score,classification_report

Training the Different - Different models

In [11]:
logistic_regression_params = {
    "penalty": "l2",                 # Options: 'l1', 'l2', 'elasticnet', 'none'
    "dual": False,                   # Use dual or primal formulation
    "C": 1.0,                        # Inverse of regularization strength
    "solver": "lbfgs",               # Optimization algorithm ('newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga')
    "max_iter": 200,                 # Maximum number of iterations
    "multi_class": "auto",           # Options: 'auto', 'ovr', 'multinomial'
    "fit_intercept": True, }

In [12]:
lr_model=LogisticRegression(**logistic_regression_params)
lr_model.fit(X_train,y_train)

/Users/sanju/Documents/DS/MLOps/MLOps_udemy/myenv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/Users/sanju/Documents/DS/MLOps/MLOps_udemy/myenv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=200, multi_class='auto')

## Training the DecisionTreeClassifier

In [13]:
decision_tree_params = {
    "criterion": "gini",             # Options: 'gini', 'entropy'
    "splitter": "best",              # Options: 'best', 'random'
    "max_depth": 5,                  # Default: None (no limit)
    "min_samples_split": 4,          # Minimum samples required to split an internal node
    "min_samples_leaf": 1,           # Minimum samples required to be at a leaf node
    "max_features": None,            # Number of features to consider when looking for the best split
    "max_leaf_nodes": None,          # Maximum number of leaf nodes in the tree
    "min_impurity_decrease": 0.0,    # A split happens if this impurity decrease is met
    "random_state": 42               # Seed for reproducibility
}

ds_model=DecisionTreeClassifier(**decision_tree_params)
ds_model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5, min_samples_split=4, random_state=42)

## Training the RandomForestClassifier

In [14]:
random_forest_params = {
    "n_estimators": 100,             # Number of trees in the forest
    "criterion": "gini",             # Options: 'gini', 'entropy', 'log_loss'
    "max_depth": None,               # Maximum depth of the tree (default is unlimited)
    "min_samples_split": 2,          # Minimum number of samples required to split an internal node
    "min_samples_leaf": 1,           # Minimum number of samples required to be at a leaf node
    "min_weight_fraction_leaf": 0.0, # Minimum weighted fraction of the sum total of weights at a leaf node
    "max_features": "sqrt",          # Number of features to consider when looking for the best split ('auto', 'sqrt', 'log2')
    "max_leaf_nodes": None,          # Maximum number of leaf nodes in the tree
    "bootstrap": True,               # Whether bootstrap samples are used when building trees
    "oob_score": False,              # Whether to use out-of-bag samples to estimate generalization accuracy
    "n_jobs": -1,                    # Number of jobs to run in parallel (-1 means using all processors)
    "random_state": 42,              # Seed for reproducibility
    "verbose": 0,                    # Controls the verbosity when fitting and predicting
    "warm_start": False,             # Reuse the solution of the previous call to fit
    "class_weight": None             # Weights associated with classes ('balanced', 'balanced_subsample', or None)
}

rb_model=RandomForestClassifier(**random_forest_params)
rb_model.fit(X_train,y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [15]:
y_pred=lr_model.predict(X_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0])

In [16]:
f1score=f1_score(y_test,y_pred)

In [17]:
accuracy=accuracy_score(y_test,y_pred)

In [18]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



## AS now the Work of the Prediction is done MLflow comes in role

In [19]:
import mlflow

In [20]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")

In [21]:
mlflow.set_experiment("Breast-Cancer-model")

<Experiment: artifact_location='mlflow-artifacts:/932244877964290976', creation_time=1729599462130, experiment_id='932244877964290976', last_update_time=1729599462130, lifecycle_stage='active', name='Breast-Cancer-model', tags={}>

In [22]:
with mlflow.start_run():
    ## loging the logistic model params
    mlflow.log_params(logistic_regression_params)

    ##loging the Accurracing 
    mlflow.log_metric("accuracy",accuracy)
    mlflow.log_metric("f1_score",f1score)

    ## logging the model
    mlflow.sklearn.log_model(
        sk_model=lr_model,
        artifact_path="Lr-model"
    )

2024/10/23 08:42:17 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2024/10/23 08:42:17 INFO mlflow.tracking._tracking_service.client: 🏃 View run big-bass-811 at: http://127.0.0.1:5000/#/experiments/932244877964290976/runs/d17f45f142fb4fd1aaaa68a4743ba110.
2024/10/23 08:42:17 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932244877964290976.


### Now remaining two models also goiing to run after that They will add on mlflow for Experimental Tracking 

In [23]:
ds_y_pred=ds_model.predict(X_test)
rb_y_pred=rb_model.predict(X_test)
print(ds_y_pred)


[1 0 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 0 1 0
 1 1 0]


In [24]:
ds_accuracy=accuracy_score(y_test,ds_y_pred)
rb_accuracy=accuracy_score(y_test,rb_y_pred)

In [25]:
ds_accuracy

0.9473684210526315

In [26]:
rb_accuracy

0.9649122807017544

In [27]:
ds_classification_report=classification_report(y_test,ds_y_pred)
rb_classification_report=classification_report(y_test,rb_y_pred)


In [28]:
f1_score(y_test,np.array(rb_y_pred))

np.float64(0.9722222222222222)

In [29]:
ds_f1_score=f1_score(y_test,ds_y_pred)
rb_f1_score=f1_score(y_test,rb_y_pred)

In [30]:
## now adding the another model for the mlflow for experimental tracking  of Decision tree 
with mlflow.start_run():
    ## log the params
    mlflow.log_params(decision_tree_params)

    ##log the tagg
    # mlflow.log_tag("about model","This is Decsison tree model")

    ##log the metrics
    mlflow.log_metric("accuracy",ds_accuracy)
    mlflow.log_metric("f1_score",ds_f1_score)

    ## log the model
    mlflow.sklearn.log_model(
        sk_model=ds_model,
        artifact_path="Decision-tree-path"
    )


2024/10/23 08:42:19 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2024/10/23 08:42:19 INFO mlflow.tracking._tracking_service.client: 🏃 View run rare-loon-287 at: http://127.0.0.1:5000/#/experiments/932244877964290976/runs/1fc618eb1c4741f9b2c6b25aa1f8054b.
2024/10/23 08:42:19 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932244877964290976.


### For Doing the Prediciton for the new data there is two ways....

In [32]:
##1.... 
import mlflow
logged_model = 'runs:/c8592c92229048419aca7776b4c12f6c/Decision-tree-path'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)


data=X_test

# Predict on a Pandas DataFrame.
import pandas as pd
new_pred=loaded_model.predict(pd.DataFrame(data))

In [33]:
accuracy_score(y_test,new_pred)

0.9473684210526315

In [ ]:
## as this is giving good accuracy after the testing as well now  we can register this  model....